version: "3"

services:
  api:
    image: calendar/api
    container_name: calendarapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /start-reload.sh
    ports:
      - 80:80
    volumes:
      - ${PWD}/:/app
    env_file:
      - .env
