"""add label column

Revision ID: b427d112b008
Revises: 61c683ce9ed6
Create Date: 2020-10-19 18:45:44.880810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b427d112b008'
down_revision = '61c683ce9ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'label')
    # ### end Alembic commands ###
