"""revert  base model

Revision ID: d59ec05e6312
Revises: e7626eb311c3
Create Date: 2020-10-19 19:09:38.480863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59ec05e6312'
down_revision = 'e7626eb311c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
